<?php
$escape = static fn (mixed $value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$errors = $adminState['errors'];
$values = $adminState['values'];
$filters = $adminState['historyFilters'];
?>
<section class="admin-hero"><div class="container"><p class="eyebrow">Private Jet Executive</p><h1>Invoice administration</h1><p class="lead">Create and deliver a polished PDF invoice, or review your invoice history.</p></div></section>
<section class="section section--pearl"><div class="container admin-shell">
<?php if (!$adminState['authenticated']): ?>
    <form class="admin-login" method="post" action="/admin/invoices" novalidate><input type="hidden" name="admin_action" value="login"><input type="hidden" name="csrf_token" value="<?= $escape($adminState['csrfToken']) ?>"><p class="eyebrow eyebrow--dark">Secure access</p><h2>Sign in to continue.</h2><?php if (isset($errors['_form'])): ?><p class="form-notice form-notice--error"><?= $escape($errors['_form']) ?></p><?php endif; ?><div class="field"><label for="admin_username">Username</label><input id="admin_username" name="username" autocomplete="username" required></div><div class="field"><label for="admin_password">Password</label><input id="admin_password" name="password" type="password" autocomplete="current-password" required></div><button class="button" type="submit">Sign in</button></form>
<?php else: ?>
    <div class="admin-heading"><div><p class="eyebrow eyebrow--dark">Invoice workspace</p><h2><?= $adminState['tab'] === 'history' ? 'Recent invoices.' : 'Create an invoice.' ?></h2><p>PDF invoices are delivered to the customer email address and copied to the internal team.</p></div><form method="post" action="/admin/invoices"><input type="hidden" name="admin_action" value="logout"><input type="hidden" name="csrf_token" value="<?= $escape($adminState['csrfToken']) ?>"><button class="text-link" type="submit">Sign out</button></form></div>
    <nav class="admin-tabs" aria-label="Invoice workspace"><a href="/admin/invoices" class="<?= $adminState['tab'] === 'create' ? 'admin-tabs__link--active' : '' ?>">Create invoice</a><a href="/admin/invoices?tab=history" class="<?= $adminState['tab'] === 'history' ? 'admin-tabs__link--active' : '' ?>">Recent invoices</a></nav>
    <?php if (isset($errors['_form'])): ?><p class="form-notice form-notice--error"><?= $escape($errors['_form']) ?></p><?php endif; ?>
    <?php if ($adminState['tab'] === 'create'): ?>
    <form class="inquiry-form inquiry-form--light admin-form" method="post" action="/admin/invoices" novalidate data-invoice-form><input type="hidden" name="admin_action" value="create"><input type="hidden" name="csrf_token" value="<?= $escape($adminState['csrfToken']) ?>"><input type="hidden" name="invoice_request_token" value="<?= $escape($adminState['invoiceRequestToken']) ?>">
        <div class="form-grid">
            <div class="field"><label for="invoice_recipient">Customer name</label><input id="invoice_recipient" name="invoice_recipient" maxlength="180" placeholder="Client name or company" required value="<?= $escape($values['invoice_recipient'] ?? '') ?>"><?php if (isset($errors['invoice_recipient'])): ?><small class="field-error"><?= $escape($errors['invoice_recipient']) ?></small><?php endif; ?></div>
            <div class="field"><label for="recipient_email">Email address</label><input id="recipient_email" name="recipient_email" type="email" maxlength="254" autocomplete="email" required value="<?= $escape($values['recipient_email'] ?? '') ?>"><?php if (isset($errors['recipient_email'])): ?><small class="field-error"><?= $escape($errors['recipient_email']) ?></small><?php endif; ?></div>
            <div class="field field--phone"><label for="recipient_country_code">Contact number <span class="optional">Optional</span></label><div class="phone-group"><select id="recipient_country_code" name="recipient_country_code" aria-label="Customer country calling code" data-country-picker><option value="">Country code</option><?php $selectedCountry = $values['recipient_country_code'] ?? ''; require dirname(__DIR__) . '/partials/country-options.php'; ?></select><input id="recipient_phone" name="recipient_phone" type="tel" inputmode="numeric" pattern="[0-9]*" autocomplete="tel-national" placeholder="Phone number" value="<?= $escape($values['recipient_phone'] ?? '') ?>"></div><?php if (isset($errors['recipient_phone'])): ?><small class="field-error"><?= $escape($errors['recipient_phone']) ?></small><?php endif; ?></div>
            <div class="field"><label for="journey_type">Journey type</label><select id="journey_type" name="journey_type" data-invoice-journey required><option value="one_way" <?= ($values['journey_type'] ?? 'one_way') === 'one_way' ? 'selected' : '' ?>>One way</option><option value="return" <?= ($values['journey_type'] ?? '') === 'return' ? 'selected' : '' ?>>Return</option></select><?php if (isset($errors['journey_type'])): ?><small class="field-error"><?= $escape($errors['journey_type']) ?></small><?php endif; ?></div>
            <div class="field"><label for="route">Route</label><input id="route" name="route" maxlength="180" placeholder="Tangerang (CGK) - Singapore (SIN)" required value="<?= $escape($values['route'] ?? '') ?>"><?php if (isset($errors['route'])): ?><small class="field-error"><?= $escape($errors['route']) ?></small><?php endif; ?></div>
            <div class="field"><label for="outbound_at">Outbound flight</label><input id="outbound_at" name="outbound_at" type="datetime-local" required value="<?= $escape(isset($values['outbound_at']) ? str_replace(' ', 'T', substr($values['outbound_at'], 0, 16)) : '') ?>"><?php if (isset($errors['outbound_at'])): ?><small class="field-error"><?= $escape($errors['outbound_at']) ?></small><?php endif; ?></div>
            <div class="field" data-return-field><label for="return_at">Return flight</label><input id="return_at" name="return_at" type="datetime-local" value="<?= $escape(isset($values['return_at']) ? str_replace(' ', 'T', substr($values['return_at'], 0, 16)) : '') ?>"><?php if (isset($errors['return_at'])): ?><small class="field-error"><?= $escape($errors['return_at']) ?></small><?php endif; ?></div>
            <div class="field"><label for="aircraft_type">Aircraft type</label><input id="aircraft_type" name="aircraft_type" maxlength="100" placeholder="Gulfstream G650" required value="<?= $escape($values['aircraft_type'] ?? '') ?>"><?php if (isset($errors['aircraft_type'])): ?><small class="field-error"><?= $escape($errors['aircraft_type']) ?></small><?php endif; ?></div>
            <div class="field"><label for="capacity">Aircraft capacity</label><input id="capacity" name="capacity" type="number" min="1" max="999" inputmode="numeric" placeholder="14" required value="<?= $escape($values['capacity'] ?? '') ?>"><?php if (isset($errors['capacity'])): ?><small class="field-error"><?= $escape($errors['capacity']) ?></small><?php endif; ?></div>
            <div class="field field--full"><label for="additional_request">Additional request <span class="optional">Optional</span></label><textarea id="additional_request" name="additional_request" maxlength="1500" placeholder="Catering, ground transport, preferred FBO or other requirements."><?= $escape($values['additional_request'] ?? '') ?></textarea><?php if (isset($errors['additional_request'])): ?><small class="field-error"><?= $escape($errors['additional_request']) ?></small><?php endif; ?></div>
            <div class="field"><label for="total_amount">Total amount (USD)</label><input id="total_amount" name="total_amount" data-currency-input inputmode="decimal" autocomplete="off" placeholder="100,000.00" required value="<?= $escape($values['total_amount'] ?? '') ?>"><?php if (isset($errors['total_amount'])): ?><small class="field-error"><?= $escape($errors['total_amount']) ?></small><?php endif; ?></div>
            <div class="field amount-words"><label>Amount in words</label><output data-amount-words><?= isset($values['total_cents']) ? $escape(\App\Invoice\InvoiceData::words((int) $values['total_cents'])) : 'Enter a total amount to preview the wording.' ?></output></div>
        </div>
        <div class="form-submit"><button class="button" type="submit" data-invoice-submit>Generate and email PDF invoice</button><p>The PDF is sent from noreply@privatejetexecutive.com, BCC'd to the internal team, and also downloads here.</p></div>
    </form>
    <?php else: ?>
    <form class="admin-filter" method="get" action="/admin/invoices"><input type="hidden" name="tab" value="history"><div class="field"><label for="sort">Sort by</label><select id="sort" name="sort"><option value="generated_at" <?= ($filters['sort'] ?? '') === 'generated_at' ? 'selected' : '' ?>>Generated date</option><option value="due_at" <?= ($filters['sort'] ?? '') === 'due_at' ? 'selected' : '' ?>>Due date</option></select></div><div class="field"><label for="direction">Order</label><select id="direction" name="direction"><option value="desc" <?= ($filters['direction'] ?? '') === 'desc' ? 'selected' : '' ?>>Newest first</option><option value="asc" <?= ($filters['direction'] ?? '') === 'asc' ? 'selected' : '' ?>>Oldest first</option></select></div><div class="field"><label for="date_field">Date range uses</label><select id="date_field" name="date_field"><option value="generated_at" <?= ($filters['date_field'] ?? '') === 'generated_at' ? 'selected' : '' ?>>Generated date</option><option value="due_at" <?= ($filters['date_field'] ?? '') === 'due_at' ? 'selected' : '' ?>>Due date</option></select></div><div class="field"><label for="from">From</label><input id="from" name="from" type="date" value="<?= $escape($filters['from'] ?? '') ?>"></div><div class="field"><label for="to">To</label><input id="to" name="to" type="date" value="<?= $escape($filters['to'] ?? '') ?>"></div><div class="form-submit"><button class="button" type="submit">Apply filters</button><a class="text-link" href="/admin/invoices?tab=history">Clear filters</a></div></form>
    <section class="admin-history"><table><thead><tr><th>Invoice</th><th>Issued to</th><th>Email</th><th>Route</th><th>Aircraft</th><th>Total</th><th>Due</th><th>Generated</th></tr></thead><tbody><?php if ($adminState['invoices'] === []): ?><tr><td colspan="8">No invoices match this filter.</td></tr><?php else: ?><?php foreach ($adminState['invoices'] as $invoice): ?><tr><td><?= $escape($invoice['invoice_number']) ?></td><td><?= $escape($invoice['invoice_recipient']) ?></td><td><?= $escape($invoice['recipient_email']) ?></td><td><?= $escape($invoice['route']) ?></td><td><?= $escape($invoice['aircraft_type']) ?></td><td><?= $escape(\App\Invoice\InvoiceData::usd((int) $invoice['total_usd_cents'])) ?></td><td><?= $escape((new DateTimeImmutable((string) $invoice['due_at'], new DateTimeZone('Asia/Jakarta')))->format('d M Y, H:i')) ?> UTC+7</td><td><?= $escape((new DateTimeImmutable((string) $invoice['generated_at'], new DateTimeZone('Asia/Jakarta')))->format('d M Y, H:i')) ?> UTC+7</td></tr><?php endforeach; ?><?php endif; ?></tbody></table></section>
    <?php endif; ?>
<?php endif; ?>
</div></section>
