<section class="page-hero"><div class="container page-hero__content"><p class="eyebrow">Privacy</p><h1>Your information, handled with care.</h1><p class="lead">This policy explains how Private Jet Executive handles personal information shared through this website.</p></div></section>

<section class="section section--pearl"><article class="container legal-copy">
    <p class="legal-updated">Last updated: 25 September 2026</p>
    <p>Private Jet Executive respects the privacy of clients, prospective clients and website visitors. This Privacy Policy describes the information we collect, why we use it, and the choices available to you. It applies to this website and to enquiries submitted through it.</p>
    <h2>Information we collect</h2><p>When you contact us or request a charter, you may provide your name, email address, telephone number, proposed route, dates, passenger numbers and any other information you choose to include. We also process limited technical information needed to operate and secure the website, such as session data and request logs.</p>
    <h2>How we use information</h2><ul><li>To respond to enquiries and discuss possible charter arrangements.</li><li>To communicate about an active request, including confirmation and follow-up.</li><li>To maintain the security, performance and integrity of our website and services.</li><li>To meet applicable legal, accounting or regulatory obligations.</li></ul>
    <h2>Sharing and international arrangements</h2><p>We may share relevant information with service providers, aviation operators or professional advisers only where it is necessary to respond to or progress your request, comply with law, or protect our rights and operations. Aviation arrangements can involve providers in different jurisdictions. We do not sell personal information.</p>
    <h2>Retention and security</h2><p>We retain information only for as long as reasonably necessary for the purposes described above, including record-keeping and legal obligations. We use reasonable organisational and technical measures to protect information, but no internet transmission or storage system can be guaranteed completely secure.</p>
    <h2>Your choices</h2><p>You may ask us to access, correct, update or delete personal information we hold about you, subject to applicable law and legitimate record-retention needs. To make a request or ask a privacy question, email <a href="mailto:charter@privatejetexecutive.com">charter@privatejetexecutive.com</a>.</p>
    <h2>Children and policy updates</h2><p>This website is not intended for children to submit personal information. We may update this policy when our practices or legal requirements change; the date above will show the latest revision.</p>
</article></section>
