<!doctype html><html lang="en"><head><meta charset="utf-8"><style>
@page { margin: 34px 38px 42px; } body { color:#1b1d21; font: 11px/1.55 DejaVu Sans, sans-serif; } .header { background:#0a0f1c; color:#f8f7f4; padding:24px 28px; } .logo { width:230px; max-height:78px; object-fit:contain; object-position:left center; } .brand { color:#eadcc8; font-size:12px; letter-spacing:2px; text-transform:uppercase; } .invoice { color:#d4af7c; font-size:26px; letter-spacing:1px; text-align:right; } .subtle { color:#a7a29a; font-size:9px; } table { width:100%; border-collapse:collapse; } .meta { margin:24px 0 28px; } .meta td { width:50%; vertical-align:top; } .label { color:#8e7656; font-size:8px; font-weight:bold; letter-spacing:1.2px; text-transform:uppercase; } .value { margin-top:4px; font-size:12px; } .section-title { margin:0; padding:10px 12px; color:#f8f7f4; background:#1b1d21; font-size:9px; letter-spacing:1.2px; text-transform:uppercase; } .details td { padding:10px 12px; border-bottom:1px solid #e3ded5; vertical-align:top; } .details td:first-child { width:36%; color:#6e6861; font-weight:bold; } .amount { margin-top:24px; border:1px solid #d4af7c; } .amount td { padding:14px 16px; } .amount .total { color:#0a0f1c; background:#eadcc8; font-size:19px; font-weight:bold; text-align:right; } .words { color:#5c5144; font-style:italic; } .payment { margin-top:24px; padding:18px; border-left:3px solid #d4af7c; background:#f5f2ed; } .payment p { margin:3px 0; } .footer { margin-top:30px; padding-top:12px; border-top:1px solid #d4af7c; color:#736d65; font-size:8.5px; } </style></head><body>
<table class="header"><tr><td><?php if ($logoData !== ''): ?><img class="logo" src="<?= $logoData ?>" alt="Private Jet Executive"><?php else: ?><div class="brand">Private Jet Executive</div><?php endif; ?></td><td class="invoice">INVOICE<br><span class="subtle"><?= $escape($invoice['invoice_number']) ?></span></td></tr></table>
<table class="meta"><tr><td><div class="label">Issued by</div><div class="value">Private Jet Executive<br>Semarang, Indonesia<br>charter@privatejetexecutive.com</div></td><td style="text-align:right"><div class="label">Generated</div><div class="value"><?= $escape($generatedAt->format('l, d F Y; H:i')) ?> UTC+7</div><div class="label" style="margin-top:12px">Payment due</div><div class="value"><?= $escape((new DateTimeImmutable((string) $invoice['due_at'], new DateTimeZone('Asia/Jakarta')))->format('l, d F Y; H:i')) ?> UTC+7</div><div class="label" style="margin-top:12px">Payment status</div><div class="value">Pending payment</div></td></tr></table>
<h2 class="section-title">Flight details</h2><table class="details"><tr><td>Service description</td><td>Private charter flight arrangement</td></tr><tr><td>Journey type</td><td><?= $invoice['journey_type'] === 'return' ? 'Return' : 'One way' ?></td></tr><tr><td>Route</td><td><?= $escape($invoice['route']) ?></td></tr><tr><td>Outbound flight</td><td><?= $escape((new DateTimeImmutable((string) $invoice['outbound_at'], new DateTimeZone('Asia/Jakarta')))->format('l, d F Y; H:i')) ?> UTC+7</td></tr><?php if ($invoice['journey_type'] === 'return'): ?><tr><td>Return flight</td><td><?= $escape((new DateTimeImmutable((string) $invoice['return_at'], new DateTimeZone('Asia/Jakarta')))->format('l, d F Y; H:i')) ?> UTC+7</td></tr><?php endif; ?><tr><td>Aircraft type</td><td><?= $escape($invoice['aircraft_type']) ?></td></tr><tr><td>Aircraft capacity</td><td><?= $escape($invoice['capacity']) ?> passengers</td></tr><?php if ((string) $invoice['additional_request'] !== ''): ?><tr><td>Additional request</td><td><?= nl2br($escape($invoice['additional_request'])) ?></td></tr><?php endif; ?></table>
<table class="amount"><tr><td><div class="label">Total amount due</div><div class="words">Amount in words: <?= $escape($amountWords) ?></div></td><td class="total"><?= $escape($amount) ?></td></tr></table>
<div class="payment"><div class="label">Payment instructions</div><p><strong>Bank:</strong> OCBC NISP Indonesia (PT Bank OCBC NISP Tbk)</p><p><strong>Account Holder:</strong> PT Shiro Xpress International</p><p><strong>Account Number:</strong> 030800010248</p><p><strong>SWIFT Code:</strong> NISPIDJAXXX</p><p><strong>Country:</strong> Indonesia</p><p><strong>Payment reference:</strong> <?= $escape($invoice['invoice_number']) ?></p><p style="margin-top:10px"><strong>Note:</strong> All bank charges and transfer fees are to be borne by the sender. Please include the invoice number as your payment reference.</p></div>
<div class="footer">This invoice is issued by Private Jet Executive. Payment is due by the date shown above. Flight arrangements remain subject to the applicable written confirmation, operational requirements and receipt of cleared funds.</div>
</body></html>
